import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      maxWidth: {
        container: "var(--container-lg, var(--container))",
        content: "var(--container-lg, var(--container))",
        wide: "var(--container-xl, 1280px)",
      },
      spacing: {
        micro: "var(--space-micro)",
        tight: "var(--space-tight)",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-07, var(--s7))",
        8: "var(--space-08, var(--s8))",
        9: "var(--space-09, var(--s9))",
        gutter: "var(--gutter-mobile)",
        "gutter-tablet": "var(--gutter-tablet)",
        "gutter-desktop": "var(--gutter-desktop)",
      },
      fontSize: {
        xs: ["var(--font-size-1, var(--text-sm))", { lineHeight: "var(--line-1, var(--lh-sm))" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--lh-sm)" }],
        base: ["var(--text-base)", { lineHeight: "var(--lh-md)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--lh-md)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--lh-lg)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--lh-xl)" }],
        caption: ["var(--text-caption-size, var(--font-size-1))", { lineHeight: "var(--text-caption-line, var(--line-1))" }],
        "body-sm": ["var(--text-body-sm-size, var(--font-size-2))", { lineHeight: "var(--text-body-sm-line, var(--line-2))" }],
        body: ["var(--text-body-size, var(--font-size-3))", { lineHeight: "var(--text-body-line, var(--line-3))" }],
        title: ["var(--text-title-size, var(--font-size-4))", { lineHeight: "var(--text-title-line, var(--line-4))" }],
        display: ["var(--text-display-size, var(--font-size-6))", { lineHeight: "var(--text-display-line, var(--line-5))" }],
      },
      lineHeight: {
        sm: "var(--lh-sm)",
        md: "var(--lh-md)",
        lg: "var(--lh-lg)",
        xl: "var(--lh-xl)",
        1: "var(--line-1, var(--lh-sm))",
        2: "var(--line-2, var(--lh-md))",
        3: "var(--line-3, 24px)",
        4: "var(--line-4, 30px)",
        5: "var(--line-5, var(--lh-xl))",
        heading: "var(--lh-heading-display, var(--line-5))",
        compact: "var(--lh-ui-compact, var(--line-2))",
        tight: "var(--lh-ui-tight, 18px)",
      },
      colors: {
        accent: "var(--color-accent, var(--accent))",
        accentHover: "var(--color-accent-hover, var(--accent-hover))",
        accentSoft: "var(--color-accent-soft, var(--accent-soft))",
        onAccent: "var(--color-on-accent, var(--on-accent))",
        focus: "var(--color-focus, var(--accent))",

        canvas: "var(--color-canvas, var(--canvas))",
        surface: "var(--color-surface, var(--surface))",
        surfaceMuted: "var(--color-surface-2, var(--surface-muted))",
        surfaceRaised: "var(--color-surface-raised, var(--surface-raised))",

        text: "var(--color-text, var(--text))",
        textMuted: "var(--color-text-muted, var(--text-muted))",
        textSubtle: "var(--color-text-subtle, var(--text-subtle))",

        border: "var(--color-border, var(--border))",
        borderStrong: "var(--color-border-strong, var(--border-strong))",

        successBg: "var(--color-success-bg, var(--success-bg))",
        successText: "var(--color-success, var(--success-text))",
        dangerBg: "var(--color-danger-bg, var(--danger-bg))",
        dangerText: "var(--color-danger, var(--danger-text))",
        warningBg: "var(--color-warning-bg, var(--warning-bg))",
        warningText: "var(--color-warning, var(--warning-text))",

        swatch1: "var(--swatch-1)",
        swatch2: "var(--swatch-2)",
        swatch3: "var(--swatch-3)",
        swatch4: "var(--swatch-4)",
      },
      borderRadius: {
        inline: "var(--radius-inline)",
        item: "var(--radius-item)",
        card: "var(--radius-card)",
        surface: "var(--radius-surface)",
        pill: "var(--radius-pill)",
        1: "var(--radius-1, 4px)",
        2: "var(--radius-2, 6px)",
        3: "var(--radius-3, 12px)",
        4: "var(--radius-4, 18px)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
      },
      fontFamily: {
        body: ["var(--font-body-family)"],
        heading: ["var(--font-heading-family)"],
        editorial: ["var(--font-editorial-family)"],
        ui: ["var(--font-ui-family, var(--font-body-family))"],
      },
      fontWeight: {
        body: "var(--font-body-weight)",
        heading: "var(--font-heading-weight)",
        editorial: "var(--font-editorial-weight)",
        ui: "var(--font-ui-weight, 600)",
      },
      height: {
        "control-sm": "var(--control-sm)",
        "control-md": "var(--control-md)",
        "control-lg": "var(--control-lg)",
        header: "var(--header-height)",
      },
      minHeight: {
        "control-sm": "var(--control-sm)",
        "control-md": "var(--control-md)",
        "control-lg": "var(--control-lg)",
      },
      zIndex: {
        base: "var(--z-base)",
        sticky: "var(--z-sticky)",
        popover: "var(--z-popover)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
        tooltip: "var(--z-tooltip)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        emphasis: "var(--ease-emphasis)",
      },
    },
  },
  plugins: [],
};

export default config;
